import type { EvidenceEnvelope } from './evidence-map';

// Demo envelope: three rows, one per intake path, to exercise the
// playback screen's path-specific source-citation footer. Mirrors the
// ConsultCo worked examples from Q8 §3.

export const consultcoEvidenceEnvelope: EvidenceEnvelope = {
  orgName: 'ConsultCo',
  orgSector: 'professional_services',
  totalBaselineTco2e: 112,
  meta: {
    engineVersion: 'automacc-v3.0.0',
    factorsEdition: 'NGER 2025',
    producedAt: '2026-05-13T22:10:00+10:00',
  },
  rows: [
    {
      rowId: 'row-1',
      label: 'Electricity — lighting, HVAC, office equipment',
      path: 'manual',
      confidence: 'H',
      userConfirmed: false,
      userEdited: false,
      source: {
        path: 'manual',
        fieldKey: 'electricity_kwh_buildings',
        section: 'Buildings and power',
        rawValue: 107,
        rawUnit: 'MWh',
        conversionApplied: 'MWh × 1000',
      },
      factor: {
        name: 'NGER 2025 Scope 2 — NSW/ACT',
        value: 0.64,
        unit: 'kg CO2-e/kWh',
        edition: 'NGER 2025 (DCCEEW, August 2025)',
        publisher: 'DCCEEW',
        appliesToField: 'electricity_kwh_buildings',
      },
      computed: {
        volumeUser: 107,
        volumeUserUnit: 'MWh',
        volumeCanonical: 107000,
        tco2eEstimate: 68,
        formulaRendered: '107,000 kWh × 0.64 kg CO2-e/kWh = 68 tCO2-e per year',
      },
    },
    {
      rowId: 'row-2',
      label: 'Natural gas — space heating',
      path: 'upload',
      confidence: 'H',
      userConfirmed: false,
      userEdited: false,
      source: {
        path: 'upload',
        sourceDoc: 'gas_bill',
        filenameDisplay: 'agn-gas-2026-fy.pdf',
        pageNo: 3,
        sourceText: '12-month usage table — total 620.4 GJ (Apr 2025 – Mar 2026)',
        extractedValue: 620.4,
        extractedUnit: 'GJ',
        transformApplied: null,
      },
      factor: {
        name: 'NGER 2025 stationary natural gas',
        value: 51.53,
        unit: 'kg CO2-e/GJ',
        edition: 'NGER 2025 (DCCEEW, August 2025)',
        publisher: 'DCCEEW',
        appliesToField: 'natural_gas_gj_low_temp',
      },
      computed: {
        volumeUser: 620,
        volumeUserUnit: 'GJ',
        volumeCanonical: 620,
        tco2eEstimate: 32,
        formulaRendered: '620 GJ × 51.53 kg CO2-e/GJ = 32 tCO2-e per year',
      },
    },
    {
      rowId: 'row-3',
      label: 'Electricity — data servers',
      path: 'chatbot',
      confidence: 'L',
      userConfirmed: false,
      userEdited: false,
      source: {
        path: 'chatbot',
        turnId: 'T8_FB_Estimate',
        userAnswer: '(no volume supplied; estimated from sector default)',
        shape: 'fallback',
        bandLabel: '51–200 people',
        midpointUsed: true,
        fallbackTriggered: true,
        turnsUsed: 7,
      },
      factor: {
        name: 'NGER 2025 Scope 2 — NSW/ACT',
        value: 0.64,
        unit: 'kg CO2-e/kWh',
        edition: 'NGER 2025 (DCCEEW, August 2025)',
        publisher: 'DCCEEW',
        appliesToField: 'electricity_kwh_data_servers',
      },
      computed: {
        volumeUser: null,
        volumeUserUnit: null,
        volumeCanonical: 18750,
        tco2eEstimate: 12,
        formulaRendered: '(imputed) 18,750 kWh × 0.64 kg CO2-e/kWh = 12 tCO2-e per year — sector default applied',
      },
    },
  ],
};
