import type { Fixture } from './types';

export const consultcoFixture: Fixture = {
  orgName: 'ConsultCo',
  orgSector: 'professional_services',
  baselineRows: [
    { rowId: 'R1', source: 'electricity', endUse: 'lighting_hvac', label: 'Electricity — lighting & HVAC', tco2eEstimate: 142 },
    { rowId: 'R2', source: 'electricity', endUse: 'office_equipment', label: 'Electricity — office equipment', tco2eEstimate: 86 },
    { rowId: 'R3', source: 'electricity', endUse: 'datacentre', label: 'Electricity — data centre', tco2eEstimate: 218 },
    { rowId: 'R4', source: 'stationary_combustion', endUse: 'space_heating', label: 'Gas — space heating', tco2eEstimate: 64 },
    { rowId: 'R5', source: 'mobile_combustion', endUse: 'fleet', label: 'Fleet — petrol & diesel', tco2eEstimate: 38 },
    { rowId: 'R6', source: 'mobile_combustion', endUse: 'business_travel', label: 'Air travel — staff', tco2eEstimate: 312 },
  ],
  levers: [
    {
      leverId: 'BLT-001', name: 'LED lighting retrofit',
      applicableTo: [{ source: 'electricity', endUse: 'lighting_hvac' }],
      typicalAbatementPct: 60, capexAud: 25_000, opexDeltaAudAnnual: -8_000,
      sectorApplicability: ['professional_services', 'retail', 'healthcare'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'IEA buildings energy efficiency outlook', primarySourceYear: 2024 },
    },
    {
      leverId: 'BLT-002', name: 'HVAC controls upgrade',
      applicableTo: [{ source: 'electricity', endUse: 'lighting_hvac' }],
      typicalAbatementPct: 25, capexAud: 18_000, opexDeltaAudAnnual: -5_500,
      sectorApplicability: ['professional_services', 'retail'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'ASHRAE energy standard 90.1', primarySourceYear: 2022 },
    },
    {
      leverId: 'BLT-005', name: 'Rooftop PV',
      applicableTo: [
        { source: 'electricity', endUse: 'lighting_hvac' },
        { source: 'electricity', endUse: 'office_equipment' },
        { source: 'electricity', endUse: 'datacentre' },
      ],
      typicalAbatementPct: 35, capexAud: 180_000, opexDeltaAudAnnual: -28_000,
      sectorApplicability: ['professional_services', 'retail', 'manufacturing'],
      isEnabler: false, mutexPartners: ['BLT-006'],
      evidence: { primarySource: 'Clean Energy Council rooftop solar report', primarySourceYear: 2024 },
    },
    {
      leverId: 'BLT-006', name: 'BTM battery storage',
      applicableTo: [
        { source: 'electricity', endUse: 'lighting_hvac' },
        { source: 'electricity', endUse: 'office_equipment' },
      ],
      typicalAbatementPct: 10, capexAud: 140_000, opexDeltaAudAnnual: -6_000,
      sectorApplicability: ['professional_services', 'retail'],
      isEnabler: false, mutexPartners: ['BLT-005'],
      evidence: { primarySource: 'AEMO behind-the-meter battery study', primarySourceYear: 2023 },
    },
    {
      leverId: 'PWR-003', name: 'Solar PPA',
      applicableTo: [
        { source: 'electricity', endUse: 'lighting_hvac' },
        { source: 'electricity', endUse: 'office_equipment' },
        { source: 'electricity', endUse: 'datacentre' },
      ],
      typicalAbatementPct: 75, capexAud: 0, opexDeltaAudAnnual: 4_000,
      sectorApplicability: ['professional_services', 'retail', 'manufacturing', 'heavy_industry'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'Clean Energy Council PPA market report', primarySourceYear: 2024 },
    },
    {
      leverId: 'BLT-007', name: 'Heat pump for space heating',
      applicableTo: [{ source: 'stationary_combustion', endUse: 'space_heating' }],
      typicalAbatementPct: 80, capexAud: 32_000, opexDeltaAudAnnual: -3_500,
      sectorApplicability: ['professional_services', 'retail', 'healthcare'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'ARENA electrification of heat', primarySourceYear: 2023 },
    },
    {
      leverId: 'TRV-001', name: 'Fleet EV transition',
      applicableTo: [{ source: 'mobile_combustion', endUse: 'fleet' }],
      typicalAbatementPct: 70, capexAud: 95_000, opexDeltaAudAnnual: -12_000,
      sectorApplicability: ['professional_services', 'retail', 'logistics'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'Electric Vehicle Council fleet report', primarySourceYear: 2024 },
    },
    {
      leverId: 'TRV-002', name: 'Travel policy — rail substitution',
      applicableTo: [{ source: 'mobile_combustion', endUse: 'business_travel' }],
      typicalAbatementPct: 30, capexAud: 5_000, opexDeltaAudAnnual: -18_000,
      sectorApplicability: ['professional_services', 'finance', 'consulting'],
      isEnabler: false, mutexPartners: [],
      evidence: { primarySource: 'WRI scope 3 business travel guidance', primarySourceYear: 2023 },
    },
    {
      leverId: 'BLT-009', name: 'Green lease clause',
      applicableTo: [
        { source: 'electricity', endUse: 'lighting_hvac' },
        { source: 'electricity', endUse: 'office_equipment' },
      ],
      typicalAbatementPct: 0, capexAud: 2_000, opexDeltaAudAnnual: 0,
      sectorApplicability: ['professional_services', 'retail'],
      isEnabler: true, mutexPartners: [],
      evidence: { primarySource: 'Better Buildings Partnership green-lease toolkit', primarySourceYear: 2023 },
    },
  ],
};
