// AutoMACC v4 — lever library.
// Mirrors docs/automacc/lever-library.md. Used by Screen 2 for sanity-check
// pills on the student's capex guess and by /api/automacc/macc to ground
// Gemini Call 2.

import type { LeverRef, LeverApproach } from "./v4-types";

export const LEVER_LIBRARY: LeverRef[] = [
  // ─── 1. Stop doing ──────────────────────────────────────────────────────────
  {
    id: "stop_eliminate_business_travel",
    name: "Eliminate business travel category",
    approach: "stop",
    appliesToSourceIds: ["mob_flight_domestic_short", "mob_flight_intl_longhaul"],
    typicalCapex: { unit: "AUD per FTE", low: 200, mid: 1_000, high: 3_000 },
    opexDeltaPctOfCapex: -150,
    abatementEfficiencyPct: 60,
    lifetimeYears: 5,
    evidenceSource: "ClimateActive",
    evidenceNote: "Video-first travel policies sustained 40-70% reductions vs 2019 baseline.",
  },
  {
    id: "stop_divest_fossil_assets",
    name: "Divest fossil-fuel asset / cease operations",
    approach: "stop",
    appliesToSourceIds: ["fuel_coal_thermal", "proc_steel_bfbof"],
    typicalCapex: { unit: "AUD per t CO2/yr avoided", low: 0, mid: 20, high: 80 },
    opexDeltaPctOfCapex: -10,
    abatementEfficiencyPct: 95,
    lifetimeYears: 20,
    evidenceSource: "DCCEEW",
    evidenceNote: "Corporate boundary framing; emissions excluded from boundary date.",
  },
  {
    id: "stop_retire_ice_fleet_early",
    name: "Retire ICE fleet early (no replacement)",
    approach: "stop",
    appliesToSourceIds: ["mob_fleet_light_ice", "mob_fleet_heavy_diesel"],
    typicalCapex: { unit: "AUD per vehicle written off", low: 5_000, mid: 15_000, high: 40_000 },
    opexDeltaPctOfCapex: -25,
    abatementEfficiencyPct: 100,
    lifetimeYears: 8,
    evidenceSource: "NGER",
    evidenceNote: "Pull-forward of vehicle retirement when replacement is mode-shift, not EV.",
  },

  // ─── 2. Do more efficiently ─────────────────────────────────────────────────
  {
    id: "eff_led_retrofit",
    name: "LED + smart lighting retrofit",
    approach: "efficiency",
    appliesToSourceIds: ["elec_building"],
    typicalCapex: { unit: "AUD per m² NLA", low: 15, mid: 30, high: 60 },
    opexDeltaPctOfCapex: -25,
    abatementEfficiencyPct: 12,
    lifetimeYears: 10,
    evidenceSource: "Other",
    evidenceNote: "Sustainability Victoria LED Lighting Guide 2024; lever-db-v2 BLT-003.",
  },
  {
    id: "eff_hvac_vsd_upgrade",
    name: "HVAC efficiency upgrade (chillers, VRF, VSDs)",
    approach: "efficiency",
    appliesToSourceIds: ["elec_building"],
    typicalCapex: { unit: "AUD per kW cooling", low: 400, mid: 800, high: 1_400 },
    opexDeltaPctOfCapex: -18,
    abatementEfficiencyPct: 25,
    lifetimeYears: 15,
    evidenceSource: "Other",
    evidenceNote: "AIRAH HVAC Efficiency Guide 2024; BLT-001.",
  },
  {
    id: "eff_building_envelope",
    name: "Building envelope retrofit (insulation, glazing, sealing)",
    approach: "efficiency",
    appliesToSourceIds: ["fuel_gas_heating", "elec_building"],
    typicalCapex: { unit: "AUD per m² floor area", low: 40, mid: 120, high: 300 },
    opexDeltaPctOfCapex: -8,
    abatementEfficiencyPct: 22,
    lifetimeYears: 30,
    evidenceSource: "Other",
    evidenceNote: "NatHERS Technical Note 2024; BLT-004.",
  },
  {
    id: "eff_bms_ai_controls",
    name: "BMS recommissioning + AI predictive controls",
    approach: "efficiency",
    appliesToSourceIds: ["elec_building", "fuel_gas_heating"],
    typicalCapex: { unit: "AUD per m² NLA", low: 5, mid: 15, high: 40 },
    opexDeltaPctOfCapex: -30,
    abatementEfficiencyPct: 15,
    lifetimeYears: 10,
    evidenceSource: "Other",
    evidenceNote: "NABERS Energy Opportunity Guide 2024; BLT-007.",
  },
  {
    id: "eff_nabers_uplift",
    name: "NABERS uplift programme (rating-led optimisation)",
    approach: "efficiency",
    appliesToSourceIds: ["elec_building"],
    typicalCapex: { unit: "AUD per m² NLA", low: 4, mid: 30, high: 80 },
    opexDeltaPctOfCapex: -22,
    abatementEfficiencyPct: 30,
    lifetimeYears: 12,
    evidenceSource: "Other",
    evidenceNote: "1-2 star uplift on typical office; BLT-010.",
  },
  {
    id: "eff_motor_vfd_industrial",
    name: "Industrial motor VSD/VFD retrofit",
    approach: "efficiency",
    appliesToSourceIds: [
      "proc_aluminium_electrolysis",
      "proc_steel_bfbof",
      "proc_cement_clinker",
      "proc_mining_ventilation",
    ],
    typicalCapex: { unit: "AUD per kW motor rating", low: 80, mid: 200, high: 500 },
    opexDeltaPctOfCapex: -25,
    abatementEfficiencyPct: 18,
    lifetimeYears: 15,
    evidenceSource: "IEA",
    evidenceNote: "ARENA Industrial Energy Efficiency 2023.",
  },
  {
    id: "eff_eco_driving_telematics",
    name: "Eco-driving behavioural programme + telematics",
    approach: "efficiency",
    appliesToSourceIds: ["mob_fleet_light_ice", "mob_fleet_heavy_diesel"],
    typicalCapex: { unit: "AUD per vehicle", low: 500, mid: 1_200, high: 2_500 },
    opexDeltaPctOfCapex: -60,
    abatementEfficiencyPct: 8,
    lifetimeYears: 6,
    evidenceSource: "Other",
    evidenceNote: "Teletrac Navman AU Fleet ROI Study 2024; TRP-010.",
  },
  {
    id: "eff_logistics_route_optimisation",
    name: "AI logistics + route optimisation",
    approach: "efficiency",
    appliesToSourceIds: ["mob_fleet_heavy_diesel", "mob_fleet_light_ice"],
    typicalCapex: { unit: "AUD per vehicle", low: 400, mid: 1_000, high: 2_000 },
    opexDeltaPctOfCapex: -80,
    abatementEfficiencyPct: 12,
    lifetimeYears: 6,
    evidenceSource: "Other",
    evidenceNote: "Geotab Fleet Efficiency Benchmark 2024; TRP-007.",
  },
  {
    id: "eff_mine_ventilation_vod",
    name: "Mine ventilation-on-demand (VOD)",
    approach: "efficiency",
    appliesToSourceIds: ["proc_mining_ventilation", "proc_mining_diesel_haul"],
    typicalCapex: { unit: "AUD per mine", low: 2_000_000, mid: 10_000_000, high: 30_000_000 },
    opexDeltaPctOfCapex: -30,
    abatementEfficiencyPct: 35,
    lifetimeYears: 18,
    evidenceSource: "Other",
    evidenceNote: "MRIWA VOD 2021; OZ Minerals Prominent Hill 20% reduction 2022; IND-012.",
  },
  {
    id: "eff_process_heat_recovery",
    name: "Process heat recovery / heat integration",
    approach: "efficiency",
    appliesToSourceIds: ["fuel_gas_process_heat", "proc_cement_clinker", "proc_steel_bfbof"],
    typicalCapex: { unit: "AUD per kW thermal recovered", low: 300, mid: 700, high: 1_500 },
    opexDeltaPctOfCapex: -15,
    abatementEfficiencyPct: 12,
    lifetimeYears: 20,
    evidenceSource: "IEA",
    evidenceNote: "ARENA Industrial Process Heat Roadmap 2024.",
  },

  // ─── 3. Electrify ───────────────────────────────────────────────────────────
  {
    id: "electrify_heat_pump_space",
    name: "Heat pump for space heating (gas boiler replacement)",
    approach: "electrify",
    appliesToSourceIds: ["fuel_gas_heating"],
    typicalCapex: { unit: "AUD per kW thermal", low: 700, mid: 1_100, high: 1_800 },
    opexDeltaPctOfCapex: -8,
    abatementEfficiencyPct: 80,
    lifetimeYears: 15,
    evidenceSource: "Other",
    evidenceNote: "ARENA Buildings Electrification Technology Review 2023; BLT-002.",
  },
  {
    id: "electrify_heat_pump_water",
    name: "Heat pump hot water (gas water heater replacement)",
    approach: "electrify",
    appliesToSourceIds: ["fuel_gas_heating", "elec_building"],
    typicalCapex: { unit: "AUD per kW thermal", low: 900, mid: 1_400, high: 2_200 },
    opexDeltaPctOfCapex: -10,
    abatementEfficiencyPct: 75,
    lifetimeYears: 12,
    evidenceSource: "DCCEEW",
    evidenceNote: "CER hot water heat pump methodology; in-repo v3 lever-db.",
  },
  {
    id: "electrify_induction_cooking",
    name: "Induction cooking (commercial kitchen)",
    approach: "electrify",
    appliesToSourceIds: ["fuel_gas_heating"],
    typicalCapex: { unit: "AUD per kW thermal", low: 400, mid: 800, high: 1_400 },
    opexDeltaPctOfCapex: -5,
    abatementEfficiencyPct: 70,
    lifetimeYears: 10,
    evidenceSource: "Other",
    evidenceNote: "CEFC Commercial Kitchen Electrification 2023.",
  },
  {
    id: "electrify_ev_fleet_light",
    name: "Battery-electric light fleet (cars + LCV)",
    approach: "electrify",
    appliesToSourceIds: ["mob_fleet_light_ice"],
    typicalCapex: { unit: "AUD per vehicle (premium over ICE)", low: 15_000, mid: 25_000, high: 40_000 },
    opexDeltaPctOfCapex: -12,
    abatementEfficiencyPct: 85,
    lifetimeYears: 12,
    evidenceSource: "NGER",
    evidenceNote: "EV Council AU State of EVs 2024; TRP-001.",
  },
  {
    id: "electrify_ev_fleet_heavy",
    name: "Battery-electric heavy freight (rigid + articulated)",
    approach: "electrify",
    appliesToSourceIds: ["mob_fleet_heavy_diesel"],
    typicalCapex: { unit: "AUD per vehicle (premium)", low: 150_000, mid: 350_000, high: 500_000 },
    opexDeltaPctOfCapex: -10,
    abatementEfficiencyPct: 85,
    lifetimeYears: 12,
    evidenceSource: "NGER",
    evidenceNote: "NHVR Zero Emission Truck Trials 2024; TRP-002.",
  },
  {
    id: "electrify_forklift_warehouse",
    name: "Electric forklift / MHE (LPG replacement)",
    approach: "electrify",
    appliesToSourceIds: ["mob_fleet_forklift_lpg", "fuel_lpg_forklift"],
    typicalCapex: { unit: "AUD per unit (premium over LPG)", low: 5_000, mid: 15_000, high: 25_000 },
    opexDeltaPctOfCapex: -20,
    abatementEfficiencyPct: 90,
    lifetimeYears: 10,
    evidenceSource: "NGER",
    evidenceNote: "Toyota Material Handling AU Electric Forklift TCO 2024; TRP-008.",
  },
  {
    id: "electrify_haul_truck_mining",
    name: "Battery-electric mining haul truck",
    approach: "electrify",
    appliesToSourceIds: ["proc_mining_diesel_haul"],
    typicalCapex: {
      unit: "AUD per truck (premium + share of charging infra)",
      low: 700_000,
      mid: 1_500_000,
      high: 2_500_000,
    },
    opexDeltaPctOfCapex: -8,
    abatementEfficiencyPct: 80,
    lifetimeYears: 20,
    evidenceSource: "Other",
    evidenceNote: "MRIWA Electrification of Mine Vehicles 2023; IND-011.",
  },
  {
    id: "electrify_process_heat_lowtemp",
    name: "Electric process heat (<400°C)",
    approach: "electrify",
    appliesToSourceIds: ["fuel_gas_process_heat"],
    typicalCapex: { unit: "AUD per kW thermal", low: 600, mid: 1_200, high: 2_200 },
    opexDeltaPctOfCapex: -3,
    abatementEfficiencyPct: 75,
    lifetimeYears: 18,
    evidenceSource: "Other",
    evidenceNote: "ARENA Renewable Energy for Industrial Processes 2024.",
  },
  {
    id: "electrify_electric_arc_furnace_steel",
    name: "Electric arc furnace steelmaking (BF-BOF replacement)",
    approach: "electrify",
    appliesToSourceIds: ["proc_steel_bfbof"],
    typicalCapex: { unit: "AUD per t/yr steel capacity", low: 400, mid: 800, high: 1_500 },
    opexDeltaPctOfCapex: 2,
    abatementEfficiencyPct: 75,
    lifetimeYears: 30,
    evidenceSource: "Other",
    evidenceNote: "BlueScope ClimateAction Report 2023; IND-004.",
  },
  {
    id: "electrify_rail_freight",
    name: "Rail freight electrification (corridor + traction)",
    approach: "electrify",
    appliesToSourceIds: ["mob_rail_freight_diesel"],
    typicalCapex: { unit: "AUD per km corridor", low: 3_000_000, mid: 5_000_000, high: 8_000_000 },
    opexDeltaPctOfCapex: -4,
    abatementEfficiencyPct: 90,
    lifetimeYears: 35,
    evidenceSource: "IEA",
    evidenceNote: "Aurizon Decarbonisation Roadmap 2024; TRP-006.",
  },

  // ─── 4. Fuel switch ─────────────────────────────────────────────────────────
  {
    id: "fuel_switch_hvo_renewable_diesel",
    name: "HVO / renewable diesel (drop-in)",
    approach: "fuel_switch",
    appliesToSourceIds: ["mob_fleet_heavy_diesel", "fuel_diesel_stationary", "mob_rail_freight_diesel"],
    typicalCapex: { unit: "AUD per vehicle", low: 0, mid: 500, high: 2_000 },
    opexDeltaPctOfCapex: 40,
    abatementEfficiencyPct: 80,
    lifetimeYears: 10,
    evidenceSource: "Other",
    evidenceNote: "Neste MY Renewable Diesel 2024; BITRE Biofuels in Australia 2023; TRP-003.",
  },
  {
    id: "fuel_switch_green_hydrogen_process",
    name: "Green hydrogen for process heat / feedstock",
    approach: "fuel_switch",
    appliesToSourceIds: ["fuel_gas_process_heat", "proc_ammonia_smr", "proc_steel_bfbof"],
    typicalCapex: { unit: "AUD per kW H2 produced (electrolyser)", low: 2_000, mid: 3_500, high: 6_000 },
    opexDeltaPctOfCapex: 20,
    abatementEfficiencyPct: 90,
    lifetimeYears: 20,
    evidenceSource: "Other",
    evidenceNote: "ARENA HySupply 2022; green H2 at $4-8/kg in 2024.",
  },
  {
    id: "fuel_switch_biomethane",
    name: "Biomethane (RNG) for gas systems",
    approach: "fuel_switch",
    appliesToSourceIds: ["fuel_gas_heating", "fuel_gas_process_heat"],
    typicalCapex: { unit: "AUD per GJ/yr capacity", low: 200, mid: 600, high: 1_500 },
    opexDeltaPctOfCapex: 15,
    abatementEfficiencyPct: 80,
    lifetimeYears: 20,
    evidenceSource: "Other",
    evidenceNote: "ARENA Bioenergy Strategy 2024; TRP-004.",
  },
  {
    id: "fuel_switch_biomass_boiler",
    name: "Biomass boiler (gas/coal replacement)",
    approach: "fuel_switch",
    appliesToSourceIds: ["fuel_gas_process_heat", "fuel_coal_thermal"],
    typicalCapex: { unit: "AUD per kW thermal", low: 400, mid: 800, high: 1_400 },
    opexDeltaPctOfCapex: -2,
    abatementEfficiencyPct: 85,
    lifetimeYears: 20,
    evidenceSource: "Other",
    evidenceNote: "ARENA Bioenergy Roadmap 2024.",
  },
  {
    id: "fuel_switch_saf_aviation",
    name: "Sustainable aviation fuel (SAF) procurement",
    approach: "fuel_switch",
    appliesToSourceIds: ["mob_flight_domestic_short", "mob_flight_intl_longhaul"],
    typicalCapex: { unit: "AUD per t fuel/yr", low: 200, mid: 500, high: 1_200 },
    opexDeltaPctOfCapex: 200,
    abatementEfficiencyPct: 75,
    lifetimeYears: 10,
    evidenceSource: "Other",
    evidenceNote: "CEFC Sustainable Aviation Fuels 2024; SAF 2-4x jet fuel price.",
  },

  // ─── 5. Carbon capture ──────────────────────────────────────────────────────
  {
    id: "ccs_post_combust_cement",
    name: "Post-combustion CCS on cement kiln",
    approach: "ccs",
    appliesToSourceIds: ["proc_cement_clinker"],
    typicalCapex: { unit: "AUD per t CO2/yr capture capacity", low: 400, mid: 800, high: 1_500 },
    opexDeltaPctOfCapex: 12,
    abatementEfficiencyPct: 90,
    lifetimeYears: 25,
    evidenceSource: "IEA",
    evidenceNote: "IEA CCUS in Clean Energy Transitions 2020; Heidelberg Brevik (Norway); IND-003.",
  },
  {
    id: "ccs_gas_fired_power",
    name: "CCS on gas-fired generation / process",
    approach: "ccs",
    appliesToSourceIds: ["elec_process", "fuel_gas_process_heat"],
    typicalCapex: { unit: "AUD per kW gas capacity", low: 1_500, mid: 2_500, high: 4_000 },
    opexDeltaPctOfCapex: 10,
    abatementEfficiencyPct: 85,
    lifetimeYears: 25,
    evidenceSource: "IEA",
    evidenceNote: "Global CCS Institute Project Database 2024.",
  },
  {
    id: "ccs_methane_oxidation_vam",
    name: "Coal-mine methane oxidation (VAM + flare)",
    approach: "ccs",
    appliesToSourceIds: ["fug_coal_methane", "proc_mining_ventilation"],
    typicalCapex: {
      unit: "AUD per shaft (full VAM oxidiser)",
      low: 20_000_000,
      mid: 40_000_000,
      high: 80_000_000,
    },
    opexDeltaPctOfCapex: 5,
    abatementEfficiencyPct: 80,
    lifetimeYears: 20,
    evidenceSource: "DCCEEW",
    evidenceNote: "CER ERF Coal Mine Waste Gas Method 2022; IND-014; TRL 7.",
  },

  // ─── 6. Negative emissions ──────────────────────────────────────────────────
  {
    id: "neg_afforestation",
    name: "Afforestation / reforestation (ACCU)",
    approach: "negative",
    appliesToSourceIds: ["ag_soil_cropland", "other_landfill_mixed", "ag_beef_enteric"],
    typicalCapex: { unit: "AUD per t CO2 lifecycle credit", low: 25, mid: 40, high: 80 },
    opexDeltaPctOfCapex: 5,
    abatementEfficiencyPct: 100,
    lifetimeYears: 25,
    evidenceSource: "DCCEEW",
    evidenceNote: "ACCU spot ~A$36/t (Dec 2025 CER QCMR); CER Reforestation methodology.",
  },
  {
    id: "neg_soil_carbon",
    name: "Soil carbon sequestration (cropland + grazing)",
    approach: "negative",
    appliesToSourceIds: ["ag_soil_cropland", "ag_beef_enteric"],
    typicalCapex: { unit: "AUD per t CO2", low: 30, mid: 60, high: 120 },
    opexDeltaPctOfCapex: 8,
    abatementEfficiencyPct: 100,
    lifetimeYears: 25,
    evidenceSource: "DCCEEW",
    evidenceNote: "CER Soil Carbon Measurement Methodology; AGR-003; ±20-30% measurement uncertainty.",
  },
  {
    id: "neg_biochar",
    name: "Biochar production from biomass",
    approach: "negative",
    appliesToSourceIds: ["ag_soil_cropland", "other_organics_food"],
    typicalCapex: { unit: "AUD per t CO2", low: 80, mid: 150, high: 300 },
    opexDeltaPctOfCapex: 3,
    abatementEfficiencyPct: 100,
    lifetimeYears: 50,
    evidenceSource: "Other",
    evidenceNote: "CSIRO Biochar Research 2023; 100+ yr permanence.",
  },
  {
    id: "neg_savanna_burning",
    name: "Savanna fire management (early dry-season burns)",
    approach: "negative",
    appliesToSourceIds: ["ag_savanna_burn"],
    typicalCapex: { unit: "AUD per t CO2", low: 5, mid: 15, high: 30 },
    opexDeltaPctOfCapex: 10,
    abatementEfficiencyPct: 100,
    lifetimeYears: 15,
    evidenceSource: "DCCEEW",
    evidenceNote: "CER Savanna Fire Management methodology; AGR-004; most mature land-sector ACCU.",
  },
];

export const LEVERS_BY_ID: Record<string, LeverRef> = Object.fromEntries(
  LEVER_LIBRARY.map((l) => [l.id, l]),
);

export function leversForApproach(approach: LeverApproach): LeverRef[] {
  return LEVER_LIBRARY.filter((l) => l.approach === approach);
}

export function leversForSource(sourceId: string): LeverRef[] {
  return LEVER_LIBRARY.filter((l) => l.appliesToSourceIds.includes(sourceId));
}

export function leversForApproachAndSource(approach: LeverApproach, sourceId: string): LeverRef[] {
  return LEVER_LIBRARY.filter(
    (l) => l.approach === approach && l.appliesToSourceIds.includes(sourceId),
  );
}
