import {
  CheckBadgeIcon,
  CheckCircleIcon,
  ClockIcon,
  SparklesIcon,
  UserIcon,
} from "@heroicons/react/24/outline";
import { COLORS } from "@/lib/design-tokens";

export type EditorialStatus =
  | "editor_authored"
  | "editor_reviewed"
  | "previously_reviewed_stale"
  | "ai_drafted"
  | "user_generated";

const STATUS_CONFIG: Record<
  EditorialStatus,
  {
    label: string;
    tone: "authoritative" | "ok" | "stale" | "draft" | "user";
    Icon: typeof CheckBadgeIcon;
    title: string;
  }
> = {
  editor_authored: {
    label: "Editor-authored",
    tone: "authoritative",
    Icon: CheckBadgeIcon,
    title: "Written end-to-end by a ClimatePulse editor.",
  },
  editor_reviewed: {
    label: "Editor-reviewed",
    tone: "ok",
    Icon: CheckCircleIcon,
    title: "AI-drafted, accepted by an editor.",
  },
  previously_reviewed_stale: {
    label: "Review expired",
    tone: "stale",
    Icon: ClockIcon,
    title: "Was reviewed; review has expired (>180 days). Treat as stale.",
  },
  ai_drafted: {
    label: "AI draft — unreviewed",
    tone: "draft",
    Icon: SparklesIcon,
    title: "Model-drafted; not yet reviewed by an editor.",
  },
  user_generated: {
    label: "User-generated",
    tone: "user",
    Icon: UserIcon,
    title: "Generated by a user; not canonical.",
  },
};

const TONE_STYLES: Record<
  "authoritative" | "ok" | "stale" | "draft" | "user",
  { color: string; background: string; border: string }
> = {
  authoritative: {
    color: COLORS.forest,
    background: COLORS.sageTint,
    border: COLORS.sage,
  },
  ok: {
    color: COLORS.forestMid,
    background: COLORS.sageTint,
    border: COLORS.sage,
  },
  stale: {
    color: COLORS.inkSec,
    background: COLORS.paperDark,
    border: COLORS.border,
  },
  draft: {
    color: COLORS.plumMid,
    background: COLORS.plumLight,
    border: COLORS.plum,
  },
  user: {
    color: COLORS.inkSec,
    background: COLORS.surface,
    border: COLORS.border,
  },
};

interface Props {
  status: EditorialStatus;
  /** Compact mode drops the label and shows icon-only with title. */
  compact?: boolean;
  /** Timestamp shown after the label (e.g. "reviewed 3 days ago"). */
  timestamp?: string | null;
  className?: string;
}

/**
 * The canonical editorial-status badge for the Learn system.
 * Five states driven by the `editorial_status` column on concept_cards,
 * microsector_briefs, microsector_brief_blocks, learning_paths.
 */
export function EditorialStatusBadge({
  status,
  compact = false,
  timestamp,
  className,
}: Props) {
  const cfg = STATUS_CONFIG[status];
  const tone = TONE_STYLES[cfg.tone];
  const { Icon } = cfg;

  return (
    <span
      role="status"
      aria-label={cfg.label}
      title={cfg.title}
      className={className}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: compact ? "2px 6px" : "3px 8px",
        border: `1px solid ${tone.border}`,
        background: tone.background,
        color: tone.color,
        borderRadius: 2,
        fontSize: 11,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
        fontWeight: 500,
        lineHeight: 1,
        whiteSpace: "nowrap",
      }}
    >
      <Icon
        width={12}
        height={12}
        strokeWidth={1.6}
        aria-hidden="true"
        style={{ flex: "none" }}
      />
      {!compact && <span>{cfg.label}</span>}
      {!compact && timestamp && (
        <span style={{ opacity: 0.7, textTransform: "none", letterSpacing: 0 }}>
          {" · "}
          {timestamp}
        </span>
      )}
    </span>
  );
}
